# -*- coding: utf-8 -*-
"""OSS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1un6L_u6eEjTeK8zK4tvFgKr_gE58bKY4

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

ds1 = pd.read_csv('50_Startups.csv')
X_1 = ds1.iloc[:, :-1].values
Y_1 = ds1.iloc[:, -1].values

print(X_1)

print(Y_1)

"""## Encoding categorical data"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
CT=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[-1])],remainder='passthrough')
X_1=CT.fit_transform(X_1)

print(X_1)

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_1_train,X_1_test,Y_1_train,Y_1_test=train_test_split(X_1,Y_1,test_size=.2,random_state=0)

print(X_1_train)

print(Y_1_train)

print(X_1_test)

print(Y_1_test)

"""## Training the Multiple Linear Regression model on the Training set"""

from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(X_1_train,Y_1_train)

"""## Predicting the Test set results"""

Y_1_pred=LR.predict(X_1_test)
print(Y_1_pred)

"""## Making a single prediction (for example the profit of a startup with R&D Spend = 160000, Administration Spend = 130000, Marketing Spend = 300000 and State = 'California')"""

print(LR.predict(CT.transform([[160000,130000,300000,'California']])))

"""## Getting the final linear regression equation with the values of the coefficients"""

print(LR.coef_)
print(LR.intercept_)

"""The equation of our multiple linear regression model is:

$$\textrm{Profit} = 86.6 \times \textrm{Dummy State 1} - 873 \times \textrm{Dummy State 2} + 786 \times \textrm{Dummy State 3} + 0.773 \times \textrm{R&D Spend} + 0.0329 \times \textrm{Administration} + 0.0366 \times \textrm{Marketing Spend} + 42467.53$$

# Evaluating the Model Performance

##Comparing predicted Y values with Correct Y values
"""

np.set_printoptions(precision=2)
Y_1_pred_r = Y_1_pred.reshape(len(Y_1_pred),1)
Y_1_test_r = Y_1_test.reshape(len(Y_1_test),1)
print(np.concatenate((Y_1_pred_r,Y_1_test_r,Y_1_pred_r-Y_1_test_r),1))

"""## R<sup>2</sup>

"""

from sklearn.metrics import r2_score
print(r2_score(Y_1_test, Y_1_pred))

plt.scatter(Y_1_pred,Y_1_test,color='red')
plt.title("Multiple Linear Regression")
plt.xlabel('Y_1_test')
plt.ylabel('Y_1_pred')
plt.show()